version: '3.4'

services:

  pixum-docker:
    container_name: pixum-docker
    image: pixum-docker:2.0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/pixumuser/.Xauthority
      - ~:/home/pixumuser/
    environment:
      DISPLAY: unix${DISPLAY}
    devices:
      - /dev/dri:/dev/dri
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    command: /opt/Pixum/Univers\ photo\ Pixum
    #command: /home/pixumuser/Pixum/Univers\ photo\ Pixum/Univers\ photo\ Pixum
